### ISSUE TITLE
Kernel error message while processing QP with SRQs during close flow

### ISSUE THREAD

**Issue by Kamalheib** [SoftRoCE/rxe-dev#18]
When running ibv_srq_pingpong application the following error message appear in the dmesg.

To reproduce:
- Run in server side: ibv_srq_pingpong -n 1 -d rxe0 -g 0
- Run in client side: ibv_srq_pingpong -n 1 -d rxe0 -g 0 10.135.230.5

From dmesg:
[45295.394016] no qp matches qpn 0x1c
[45295.394021] no qp matches qpn 0x1d
[45295.394023] no qp matches qpn 0x1e
[45295.394025] no qp matches qpn 0x1f

**Comment by Kamalheib** [comment]
I investigated this issue and found that rxe_destroy_qp callback called while the QP is actively sending or receiving data.

To fix this issue rxe_destroy_qp callback need to check the qp state if != RESET and wait until the qp finish sending/receiving data and then destroy the qp.

**Comment by psebexen** [comment]
While checking if the qp state != RESET may prevent this specific error during the srq_pingpong test, I am not certain this is the best approach. In the IB spec (v1.2.1), the state diagram for QP/EE Context in 10.3.1 requires that "Destroy QP/EE Context can be called from any state and exits the state diagram". If I understand it correctly, this implies that destroy_qp can be called while actively sending and receiving data and this should be handled by the rxe_destroy_qp callback gracefully.

The particular implementation seems to be left up to the Consumer and the spec warns that, in the specific case of a QP associated with a SRQ, WQE and Data Segment leakage can occur if the Consumer does not wait for the Affiliated Asynchronous Last WQE Reached Event. I assume that the OFED pingpong implementation is correct, so this seems to be the most likely issue.

If this does not sound correct, could you please provide the OFED libibverbs version being used and I will try to replicate the error and follow the debug trace?

For reference, the recommended approach to fix this issue is to implement the call from the Consumer as follows:
1) Put QP in Error State;
2) wait for the Affiliated Asynchronous Last WQE Reached Event;
3) either: (a) drain the CQ by invoking the Poll CQ verb and either wait for CQ to be empty or the number of Poll CQ operations has exceeded CQ capacity size; or (b) post another WR that completes on the same CQ and wait for this WR to return as a WC;
4) and then invoke a Destroy QP or Reset QP.

**Comment by Kamalheib** [comment]
Hi Paul,

Sound correct.

Thanks,
Kamal

**Comment by psebexen** [comment]
I think this problem is being caused by the libibverbs ibv_srq_pingpong code itself. Inserting a pause immediately before it tries to call `pp_close_ctx()` in srq_pingpong.c prevents the dmesg event from appearing.

For reference, the message is printed from within rxe_recv.c when executing `hdr_check()`. If the destination qp of the incoming packet has already been destroyed, this check fails.

I am not sure if any changes need to be made to the rxe-dev code to solve this issue - a consumer should not call the destroy qp verb if the qp is in use.
