### ISSUE TITLE
error while running "rxe_cfg start"

### ISSUE THREAD

**Issue by sadar** [SoftRoCE/rxe-dev#45]
root@gl8:/home/gl8/Desktop/nvme_softroce/librxe-dev# rxe_cfg start
mkdir: cannot create directory `/sys/kernel/config/rdma_cm': Operation not permitted
tee: /sys/kernel/config/rdma_cm/rxe0/default_roce_mode: No such file or directory
IBOE V2
Use of uninitialized value within %eth_driver in string at /bin/rxe_cfg line 361.
  Name  Link  Driver  Speed  NMTU  IPv4_addr  RDEV  RMTU  
  eth0                       1500             rxe0  1024  (3)

**Comment by psebexen** [comment]
The first message ('mkdir: ...') indicates the most likely problem. The script expects that configfs is mounted (this can be done manually with `mount -t configfs none /sys/kernel/config` assuming the kernel was built with appropriate support).
If the error still occurs, there might be some issue with permissions. You can try executing the same command as the script to see if the directory can be created at all: `mkdir -p /sys/kernel/config/rdma_cm/rxe0`.

The next message ('tee: ... No such file') should be resolved at the same time; this is caused by the script trying to write a value to the 'default_roce_mode' file in the device's configfs directory (you can run the same command manually with `echo IBOE V2 | tee /sys/kernel/config/rdma_cm/$rxed/default_roce_mode`).

The third message is unresolved to my knowledge, but is a minor issue. This is just an error in parsing the output text in ethtool (I assume this was originally compatible with an older version of the utility) that should not affect function.

If the issue persists, it might also help if you share the contents of `/etc/udev/rules.d/10-local-ib.rules` or any ib- or roce- related files in that directory.

**Comment by sadar** [comment]
thanks for the solution, problem is solved by this script "mount -t configfs none /sys/kernel/config"
